version: '3.9'
services:
  sender:
    build: ./sender
    container_name: sender
    networks:
      test_net:
        ipv4_address: 192.168.0.10
    command: python3 sender.py
  receiver:
    build: ./receiver
    container_name: receiver
    networks:
      test_net:
        ipv4_address: 192.168.0.20
    command: python3 receiver.py
  monitor:
    build: ./monitor
    container_name: monitor
    networks:
      test_net:
        ipv4_address: 192.168.0.30
    command: python3 monitor.py
networks:
  test_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16