services:
  sender:
    build: ./sender
    container_name: sender
    networks:
      test_net:
        ipv4_address: ${IP_SENDER}
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env  
    cap_add:
      - NET_ADMIN

  receiver:
    build: ./receiver
    container_name: receiver
    networks:
      test_net:
        ipv4_address: ${IP_RECEIVER}
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env  
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./cert.pem:/app/cert.pem
    - ./key.pem:/app/key.pem
    cap_add:
      - NET_ADMIN

  monitor:
    build: ./monitor
    container_name: monitor
    networks:
      test_net:
        ipv4_address: ${IP_MONITOR}
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
    - .env  
    sysctls:
    - net.ipv4.ip_forward=1
    cap_add:
    - NET_ADMIN

networks:
  test_net:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: ${SUBNET_TEST_NET}
